trailing_comma:
  mandatory_comma: true
opt_in_rules:
  - array_init
  - conditional_returns_on_newline
  - identical_operands
  - direct_return
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - implicitly_unwrapped_optional
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  - fallthrough
  - async_without_await
  - attributes
  - comma_inheritance
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - convenience_type
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_enum_raw_value
  - explicit_init
  - flatmap_over_map_reduce
  - joined_default_parameter
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - no_extension_access_modifier
  - no_grouping_extension
  - prefer_asset_symbols
  - no_magic_numbers
  - non_overridable_class_declaration
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - override_in_extension
  - pattern_matching_keywords
  - prefer_condition_list
  - prefer_key_path
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - reduce_into
  - private_outlet
  - private_action
  - private_subject
  - redundant_nil_coalescing
  - redundant_self
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_argument
  - shorthand_optional_binding
  - sorted_enum_cases
  - sorted_first_last
  - sorted_imports
  - static_operator
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - file_name
  - file_header
  - file_name_no_space
  - file_types_order
  - first_where
  - final_test_case
  - literal_expression_end_indentation
  - function_default_parameter_at_end
  - strict_fileprivate
  - superfluous_else
  - weak_delegate
  - yoda_condition
  - multiline_call_arguments
  - unneeded_throws_rethrows
  - local_doc_comment
  - unneeded_escaping
  - unavailable_function
strict: true
