name: Deploy DocC to GitHub Pages

on:
  push:
    branches: ["main"]

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build DocC
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target vsexpr \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path vsexpr \
            --output-path ./docs

      - name: Add Redirect to Landing Page
        run: |
          echo '<script>window.location.href += "/documentation/vsexpr"</script>' > ./docs/index.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
